GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjk2LCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE2ODcwMDQ2OTYsImV4cCI6MTY4NzAwNDcxMX0.5RZ6oIpcsAx0RgViDM0Ut-dYgq7cRkpQHTOW0JJ7tEo
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "mshinr",
    "email": "email@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

###
PATCH http://localhost:5000/users/85
Content-Type: application/json

{
    "username": "batang",
    "email": "batang@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}